image:
  repository: c63eqfuv.c1.gra9.container-registry.ovh.net/gfts/webapp
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

certManager:
  enabled: true
  namespace: webapp
  installCRDs: true
  prometheus.enabled: false

service:
  type: ClusterIP
  port: 80
  targetPort: 9000

ingress:
  enabled: true
  namespace: webapp
  installController: true
  className: "webapp-nginx"
  annotations:
    cert-manager.io/issuer: letsencrypt-webapp
  hosts:
    - host: gfts.developmentseed.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - enabled: true
      hosts:
        - gfts.developmentseed.org
      secretName: tls-webapp
      certManager: true
      certManagerIssuer: letsencrypt-webapp
      certManagerEmail: info@developmentseed.org

ingress-nginx:
  controller:
    ingressClass: "webapp-nginx"
    ingressClassResource:
      name: webapp-nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/webapp-ingress-nginx"
    service:
      loadBalancerIP: "91.134.65.21"
      annotations:
        loadbalancer.openstack.org/floating-network-id: "Ext-Net"
        loadbalancer.ovhcloud.com/class: "octavia"
        loadbalancer.openstack.org/keep-floatingip: "true"
      externalTrafficPolicy: Local
  fullnameOverride: "webapp-ingress-nginx"

livenessProbe:
  httpGet:
    path: /
    port: 9000

readinessProbe:
  httpGet:
    path: /
    port: 9000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
