image:
  repository: 66gc0z34.c1.gra9.container-registry.ovh.net/gfts/webapp
  pullPolicy: Always
  tag: "latest"
  pullSecrets:
    - name: ovh-registry-credentials

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

oauth2Proxy:
  enabled: true

global:
  redis:
    password: "${OAUTH2_PROXY_REDIS_SECRET}"

oauth2-proxy:
  namespaceOverride: webapp
  ingress:
    enabled: true
    className: webapp-nginx
    pathType: Prefix
    path: /oauth2
    hosts:
      - gfts.developmentseed.org
  config:
    clientID: "gfts-bearer"
    clientSecret: "${OAUTH2_PROXY_CLIENT_SECRET}"
  redis:
    enabled: true
  sessionStorage:
    type: redis
  extraArgs:
    provider: keycloak-oidc
    oidc-issuer-url: "https://iam.ivv.desp.space/realms/desp"
    whitelist-domain: gfts.developmentseed.org
    scope: openid
    insecure-oidc-allow-unverified-email: true
    email-domain: "*"
    oidc-email-claim: "sub"
    oidc-audience-claim: "azp"
    show-debug-on-error: true

ingress:
  enabled: true
  namespace: webapp
  installController: true
  className: webapp-nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "https://gfts.developmentseed.org/oauth2/start"
    nginx.ingress.kubernetes.io/auth-url: "https://gfts.developmentseed.org/oauth2/auth"
    cert-manager.io/cluster-issuer: "letsencrypt"
  tls:
    enabled: true
    secretName: webapp-tls
  hosts:
    - host: gfts.developmentseed.org
      paths:
        - path: /
          pathType: ImplementationSpecific

ingress-nginx:
  controller:
    ingressClass: webapp-nginx
    ingressClassResource:
      name: webapp-nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/webapp-ingress-nginx"
    service:
      loadBalancerIP: "57.130.31.159"
      annotations:
        loadbalancer.ovhcloud.com/class: "octavia"
        loadbalancer.openstack.org/keep-floatingip: "true"
    config:
      disable-ipv6: "true"
      disable-ipv6-dns: "true"
      strict-validate-path-type: false # needed for letsencrypt acme challenge
  fullnameOverride: webapp-ingress-nginx

livenessProbe:
  httpGet:
    path: /
    port: 80

readinessProbe:
  httpGet:
    path: /
    port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
