apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    cert-manager.io/http01-solver-ingress-path-type: ImplementationSpecific
spec:
  acme:
    email: info@developmentseed.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: webapp-nginx
