#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: Global Fish Tracking System (GFTS) - DestinE Platform use case # The title of the book. Will be placed in the left navbar.
author: GFTS Consortium # The author of the book
copyright: "2025 Development Seed, Simula, and Ifremer" # Copyright year to be placed in the footer
logo: "./_static/logomark.svg" # A path to the book logo
only_build_toc_files: true
release: "1.0"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false
  timeout: 1000

# Add a launch button on a specific binder instance
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://notebooks.gesis.org/binder/" # The URL for your BinderHub (e.g., https://mybinder.org)
  jupyterhub_url: "http://pangeo-eosc.vm.fedcloud.eu/jupyterhub/" # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: gfts.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/destination-earth/DestinE_ESA_GFTS # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    author: GFTS Consortium
    copyright: "2025 Development Seed, Simula, and Ifremer"
    project: Global Fish Tracking System
    release: "1.0"
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_static_path:
      - _static/
    html_css_files:
      - code-style.css
      - xarray-style.css
      - service-doc.css
    html_theme: sphinx_rtd_theme
    rst_epilog: |
      .. |project| replace:: GFTS
    nitpicky: true

  extra_extensions:
    - sphinx_exercise
    - sphinx_rtd_theme
